/*

Decision Tree: A binary tree that splts the dataset until we get to leaf nodes
    At each node, we basically have a condition. 
    Given true or false, we then take a path down the tree
    Leaf Nodes are the final station for the dataset. 
    Each leaf will only have one class of data

    While this is basically a big list of if else statements, the list is generated by the computer.


    We want to minimize uncertainty, and maximize information gain.


    Decision trees can be used for binary or multi-class classification


*/